//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogInForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap @__aether_sangonomiya_kokomi_kaedehara_kazuha_gorou_and_teppei_genshin_impact_drawn_by_hitohachan__70fb0a00e1aa457b5eb39f3ca1d0a856 {
            get {
                object obj = ResourceManager.GetObject("__aether_sangonomiya_kokomi_kaedehara_kazuha_gorou_and_teppei_genshin_impact_draw" +
                        "n_by_hitohachan__70fb0a00e1aa457b5eb39f3ca1d0a856", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap @__alhaitham_genshin_impact_drawn_by_0jae__221ee8845e36917fb7de57ce65335829 {
            get {
                object obj = ResourceManager.GetObject("__alhaitham_genshin_impact_drawn_by_0jae__221ee8845e36917fb7de57ce65335829", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap @__kamisato_ayaka_and_kaedehara_kazuha_genshin_impact_drawn_by_lumi250__36288a0b4d5426a263ca1093a7ec312f {
            get {
                object obj = ResourceManager.GetObject("__kamisato_ayaka_and_kaedehara_kazuha_genshin_impact_drawn_by_lumi250__36288a0b4d" +
                        "5426a263ca1093a7ec312f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap @__kamisato_ayaka_genshin_impact_drawn_by_dinhosaur__de5dbf4911bec5ea81171dd04fca79dd {
            get {
                object obj = ResourceManager.GetObject("__kamisato_ayaka_genshin_impact_drawn_by_dinhosaur__de5dbf4911bec5ea81171dd04fca7" +
                        "9dd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap @__zhongli_and_hu_tao_genshin_impact_drawn_by_pitohuibloodbend__48e73b010932c26ae5a36fbfd47cbd22 {
            get {
                object obj = ResourceManager.GetObject("__zhongli_and_hu_tao_genshin_impact_drawn_by_pitohuibloodbend__48e73b010932c26ae5" +
                        "a36fbfd47cbd22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2h2qhm4a4jo71 {
            get {
                object obj = ResourceManager.GetObject("2h2qhm4a4jo71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _92466345_p1 {
            get {
                object obj = ResourceManager.GetObject("92466345_p1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picture1 {
            get {
                object obj = ResourceManager.GetObject("picture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
